### ISSUE TITLE
class vs ID

### ISSUE THREAD

**Issue by ad3429** [orbsini/prj-rev-bwfs-dasmoto#1]
https://github.com/orbsini/prj-rev-bwfs-dasmoto/blob/master/DasmotosArtsCrafts/index.html#L12-L26

It seems you assigned classes to your brushes, frames and paint elements however you should assign these ID's instead. While classes are better for when you want to style groups of elements the same way, id's are better suited for when you want to style unique, individual elements which is the case here for the brushes, frames and paint elements. You can read more about the difference here:

https://css-tricks.com/the-difference-between-id-and-class/

**Comment by orbsini** [comment]
Thanks for pointing this out!
