### ISSUE TITLE
excellent HTML code practices followed

### ISSUE THREAD

**Issue by ad3429** [orbsini/prj-rev-bwfs-dasmoto#3]
https://github.com/orbsini/prj-rev-bwfs-dasmoto/blob/master/DasmotosArtsCrafts/index.html#L9-L25

Your HTML is very nicely structured/organized and you followed great code practices like indenting your code appropriately, commenting the main parts, etc. Make sure to keep this up in future projects!

**Comment by orbsini** [comment]
Thanks! <3
